name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    # Download ngrok
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    # Extract ngrok
    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok

    # Authenticate ngrok
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Enable Remote Desktop (RDP)
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    # Create ngrok tunnel
    - name: Create Tunnel
      run: Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp --region=eu 3389"

    # Install Python 3.10
    - name: Install Python 3.10
      run: |
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.10.7/python-3.10.7-amd64.exe" -OutFile python-installer.exe
        Start-Process -Wait -FilePath python-installer.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_test=0"

     # Add Python to PATH manually
    - name: Add Python to Environment Variables
      run: |
        $pythonPath = [System.Environment]::GetEnvironmentVariable("ProgramFiles") + "\Python310"
        [System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";$pythonPath", [System.EnvironmentVariableTarget]::Machine)

    # Verify Python installation
    - name: Verify Python Installation
      run: python --version

    - name: Start Persistent ngrok Tunnel
      run: .\ngrok\ngrok.exe tcp --region=eu 3389 --log=stdout

